name: Deploy SQL to Fabric

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: "580dfb7a-ccbd-422b-b214-f2470a0c9a7e"
      AZURE_TENANT_ID: "00ded8cc-141f-4cac-b015-a0c42b549fb9"
      AZURE_CLIENT_SECRET: "564c4731-31bf-429b-9255-3f6a7aa2fb64"
      FABRIC_SQL_SERVER: "ztmn4aa7cswezmavudccwve7xe-t62fqs35r7euncq66hruo6b6bi.datawarehouse.fabric.microsoft.com"
      FABRIC_DATABASE: "hr_attrition_lakehouse"

    steps:
      - uses: actions/checkout@v4

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          client-secret: ${{ env.AZURE_CLIENT_SECRET }}

      - name: Run SQL Script
        run: |
          /opt/mssql-tools/bin/sqlcmd \
            -S $FABRIC_SQL_SERVER \
            -d $FABRIC_DATABASE \
            -G \
            -i ./sql/script.sql
